### ISSUE TITLE
Better notification that a notebook was shared for review

### ISSUE THREAD

**Issue by parente** [danielballan/nbexamples#14]
At present, the submit a notebook button immediately triggers a new windows to open a preview of the shared notebook. It isn't immediately apparent what the button did. Instead, have a toaster come up in the notebook saying "You shared a notebook" or the equivalent, with links to take the user to the preview and/or examples tab on the file dashboard page within it.

**Comment by danielballan** [comment]
Sounds good. Do you have an idea in mind already of where that toaster would appear? Is there another nbextension doing something like this nicely already?

**Comment by parente** [comment]
In jupyter_cms, we pop a notification for the full-page drag-drop upload feature. It appears over the top of the page for a period of time. Here's the implementation:

https://github.com/jupyter-incubator/contentmanagement/blob/master/jupyter_cms/nbextension/common/notify.js

I was thinking something like that.

**Comment by danielballan** [comment]
We should keep an eye on this, also: https://github.com/jupyter/jupyterlab/issues/689

**Comment by parente** [comment]
Alternative: Open a new browser tab pointing to the Examples tab on the notebook dashboard page and highlight the example shared/updated.

This is probably simpler. We could add the highlight information to the browser query string or hash and highlight the appropriate entry when the page loads.
