### ISSUE TITLE
Multiple locations for reviewed/unreviewed examples

### ISSUE THREAD

**Issue by ericdill** [danielballan/nbexamples#2]
What are your thoughts on allowing this extension to check multiple locations for reviewed/unreviewed examples?  One use case would be to have nbexamples point at some github (or gitlab) repository by default and then fall back to the local system in case it cannot access the example git repos.

**Comment by danielballan** [comment]
For performance reasons I think nbexamples should not try to download the
repo each time. Better to aim it and one directory and update that
directory regularly through other means, like a cronjob.
