### ISSUE TITLE
serverextension folder under site-packages is missing

### ISSUE THREAD

**Issue by hemantasingh** [danielballan/nbexamples#31]
Hi Dan,

I'm trying to configure nbexample in JupyterHub environment. But getting error in installation steps 2. 
Error : Not a directory: u'/usr/lib/python2.7/site-packages/nbexamples-0.3.1-py2.7.egg/nbexamples/static'

So manually copy the static file in nbextensions folder. Now I can see the 'Example' tab. But not sure about the serverextension folder, means the /usr/lib/python2.7/site-packages/nbextensions is missing.
Please suggest me.

**Comment by parente** [comment]
Hi @hemantasingh. Can you share the commands you're running to install and enable the extension in your JupyterHub environment?

**Comment by hemantasingh** [comment]
Hi Peter,
Thanks, error in below step 2.
1. python setup.py install                   : Complete install with Success 
2. jupyter nbextension install --py nbexamples --sys-prefix  : error 
3. jupyter nbextension enable --py nbexamples --sys-prefix
4. jupyter serverextension enable --py nbexamples --sys-prefix

**Comment by sheriferson** [comment]
@hemantasingh I don't know if you're still trying to get this to work, but I ran into the same issue, and if you can use conda to install the extension (i.e. if your JupyterHub setup is conda managed), then this gets around the issue:

```
conda install -c conda-forge nbexamples
```

**Comment by hemantasingh** [comment]
Thanks  sheriferson , issue was with my pip version.
