### ISSUE TITLE
Built bundle does not include static JS assets

### ISSUE THREAD

**Issue by parente** [danielballan/nbexamples#4]
Need to specify in MANIFEST.in and/or `include_package_data=True`.

**Comment by danielballan** [comment]
Fixed in 241f14360122660bcba0e63afb6a74c384d4fe18. Thanks, @parente. I haven't had time to deploy this internally yet, so I hadn't noticed that.

**Comment by parente** [comment]
No problem. I was talking with @gbishop who is interested in the extension for a class maybe and noticed the problem along the way.

**Comment by danielballan** [comment]
Neat. Drop me a line, @gbishop, if you get some use out of this.
