### ISSUE TITLE
Installation on jupyter HUB

### ISSUE THREAD

**Issue by jai11** [danielballan/nbexamples#8]
Can you please let me know the installation steps for jupyterhub.

I tried as given in doc but not able to see it on UI

**Comment by jai11** [comment]
can you please give the proper installation steps as only submit is getting loaded in hub, not the main extension.

**Comment by jai11** [comment]
There i an urgency .. can any one suggest a solution on this.

**Comment by jai11** [comment]
any update will be really helpful over here

**Comment by danielballan** [comment]
Hi. This is a side project for me. I do deploy it on JupyterHub. I don't have a step by step guide or an exact recollection of how I did it. What have you tried?
